### PR TITLE
add usePageVisibility hook

### PR DESCRIPTION
**Pull request by frontendphil**
Fixes https://github.com/pgilad/react-page-visibility/issues/8

I've created a `usePageVisibility` hook which essentially does exactly this. It will be exported as a named export.

```es6
import { usePageVisibility } from 'react-page-visibility'
```

`usePageVisibility` returns the current visibility state.

### CODE REVIEW

**Comment by pgilad** [comment]
Excellent job! I'll try to review it in the next 2 weeks, currently on vacation :)

**Comment by pgilad** [comment]
Hey this looks great! Can you please add a readme section on how to use it (example usage) ?

**Comment by frontendphil** [comment]
@pgilad while writing the docs I realized that a different API might be better. I've changed the hook to be called `usePageVisibility` and you simply get the current value. The handler and internal state will make sure the component re-renders when the visibility changes and thus the value will always be up-to-date.

**Comment by pgilad** [comment]
Published https://github.com/pgilad/react-page-visibility/releases/tag/v4.2.0 :clap:

**Pull request merged**
